#include "../../Protocol/ACPToolRegistry.h"
#include "../BuiltinTools.h"
#include "BlueprintQueries.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraph/EdGraphSchema.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "ScopedTransaction.h"

#define LOCTEXT_NAMESPACE "UAgent"

namespace UAgent {
namespace {
class FSetPinDefaultTool : public IACPTool {
public:
  virtual FString GetMethod() const override {
    return TEXT("_ue5/set_pin_default");
  }

  virtual bool IsReadOnly() const override { return false; }

  virtual FString GetDescription() const override {
    return TEXT("Set the default value on an input pin of a Blueprint node. "
                "Type-checked via the graph schema. For object/class/interface "
                "pins, pass an asset path like '/Engine/BasicShapes/Cube.Cube' "
                "(routed through TrySetDefaultObject); soft-object and "
                "primitive pins take the ImportText form. Empty value resets "
                "to the pin's autogenerated default.");
  }

  virtual TSharedPtr<FJsonObject> GetInputSchema() const override {
    return ParseJsonObject(LR"JSON({
					"type": "object",
					"properties": {
						"blueprintPath": { "type": "string" },
						"graphName":     { "type": "string" },
						"nodeId":        { "type": "string", "description": "GUID of the node (from read_blueprint or create_node)" },
						"pinName":       { "type": "string", "description": "Pin name on the node; must be an input pin" },
						"value":         { "type": "string", "description": "New default value. Empty resets to the pin's autogenerated default." }
					},
					"required": ["blueprintPath", "graphName", "nodeId", "pinName", "value"]
				})JSON");
  }

  virtual FToolResponse
  Execute(const TSharedPtr<FJsonObject> &Params) override {
    if (!Params.IsValid())
      return FToolResponse::InvalidParams(TEXT("missing params"));

    FString BlueprintPath, GraphName, NodeId, PinName, Value;
    Params->TryGetStringField(TEXT("blueprintPath"), BlueprintPath);
    Params->TryGetStringField(TEXT("graphName"), GraphName);
    Params->TryGetStringField(TEXT("nodeId"), NodeId);
    Params->TryGetStringField(TEXT("pinName"), PinName);
    Params->TryGetStringField(TEXT("value"), Value);

    if (BlueprintPath.IsEmpty() || GraphName.IsEmpty() || NodeId.IsEmpty() ||
        PinName.IsEmpty()) {
      return FToolResponse::InvalidParams(
          TEXT("blueprintPath, graphName, nodeId, pinName are required"));
    }

    FString Err;
    UBlueprint *BP = BlueprintAccess::LoadBlueprintByPath(BlueprintPath, Err);
    if (!BP)
      return FToolResponse::Fail(-32000, Err);

    UEdGraph *Graph = BlueprintAccess::FindGraph(BP, GraphName);
    if (!Graph) {
      return FToolResponse::Fail(
          -32000, FString::Printf(TEXT("graph '%s' not found"), *GraphName));
    }

    UEdGraphNode *Node = BlueprintAccess::FindNodeById(Graph, NodeId);
    if (!Node) {
      return FToolResponse::Fail(
          -32000, FString::Printf(TEXT("node '%s' not found"), *NodeId));
    }

    UEdGraphPin *Pin = BlueprintAccess::FindPinByName(Node, PinName);
    if (!Pin) {
      return FToolResponse::Fail(
          -32000, FString::Printf(TEXT("pin '%s' not found on %s"), *PinName,
                                  *Node->GetName()));
    }

    if (Pin->Direction != EGPD_Input) {
      return FToolResponse::Fail(
          -32000,
          FString::Printf(
              TEXT("pin '%s' is an output pin — defaults only apply to inputs"),
              *PinName));
    }

    const UEdGraphSchema *Schema = Graph->GetSchema();
    if (!Schema)
      return FToolResponse::Fail(-32000, TEXT("graph has no schema"));

    // Hard object/class/interface pins store their default in DefaultObject,
    // not DefaultValue — TrySetDefaultValue silently no-ops for them.
    // Soft-object and soft-class pins serialize the path into DefaultValue, so
    // they stay on the string path.
    const FName &Cat = Pin->PinType.PinCategory;
    const bool bObjectPin = Cat == UEdGraphSchema_K2::PC_Object ||
                            Cat == UEdGraphSchema_K2::PC_Class ||
                            Cat == UEdGraphSchema_K2::PC_Interface;

    UObject *NewDefaultObject = nullptr;
    if (bObjectPin && !Value.IsEmpty()) {
      NewDefaultObject =
          StaticLoadObject(UObject::StaticClass(), nullptr, *Value);
      if (!NewDefaultObject) {
        return FToolResponse::Fail(
            -32000,
            FString::Printf(TEXT("could not load object at '%s'"), *Value));
      }
      // For class pins, transparently unwrap a loaded Blueprint to its
      // GeneratedClass so callers can pass either '/Game/BP_Foo.BP_Foo' or
      // '/Game/BP_Foo.BP_Foo_C'.
      if (Cat == UEdGraphSchema_K2::PC_Class) {
        if (UBlueprint *LoadedBP = Cast<UBlueprint>(NewDefaultObject)) {
          NewDefaultObject = LoadedBP->GeneratedClass;
        }
      }
    }

    const FString ValidationError = Schema->IsPinDefaultValid(
        Pin, bObjectPin ? FString() : Value,
        bObjectPin ? NewDefaultObject : nullptr, FText::GetEmpty());
    if (!ValidationError.IsEmpty()) {
      return FToolResponse::Fail(
          -32000, FString::Printf(TEXT("invalid value for pin type: %s"),
                                  *ValidationError));
    }

    const FScopedTransaction Tx(
        LOCTEXT("SetPinDefaultTx", "Set Pin Default Value"));
    Node->Modify();

    if (bObjectPin) {
      Schema->TrySetDefaultObject(*Pin, NewDefaultObject);
    } else {
      Schema->TrySetDefaultValue(*Pin, Value);
    }

    FBlueprintEditorUtils::MarkBlueprintAsModified(BP);
    FKismetEditorUtilities::CompileBlueprint(BP);
    return FToolResponse::Ok();
  }
};
} // namespace

TSharedRef<IACPTool> CreateSetPinDefaultTool() {
  return MakeShared<FSetPinDefaultTool>();
}
} // namespace UAgent

#undef LOCTEXT_NAMESPACE
